services:
  - type: web
    name: still-waiting-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: WAIT_TIME
        value: "10"
      - key: ALLOW_REACTIONS
        value: "true"
      - key: ENABLE_NOTIFY
        value: "true"
      - key: MAX_CONCURRENT_MONITORING
        value: "1000"